version: '3'
services:
  api:
    image: api-windows-node
    build:
      context: .
      dockerfile: Dockerfile
    #networks:
      #- backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/src/WebSpa

  web-cli:
    image: api-windows-node
    #networks:
      #- backend
    command: sh

#networks:
  #backend:
    #driver: bridge